7 make comments controller
MatWisie/KebabFinder-API pull request #30
Opened 2024-11-15 20:58 UTC by W-Worach

#7 Made a controller with functions:
- Post comment on kebab
- Put to edit your comments
- Get all comments from kebab
- Get all user comments
- Delete comments created by user 
- Delete comments of other users by admin

Please check if swagger annotations are good 
They should be fine but you never know

2024-11-19 16:46 UTC, Wiktor-Wojciechowski approved these changes
Looks alright

2024-11-22 21:07 UTC, MatWisie requested changes
I checked every route and it seems fine but why this branch contains favourite controller (i didnt check "favourite" routes)? This is separate issue so could you please separate changes regarding favourite controller to another branch or something? Thank you :)

2024-11-30 11:50 UTC, W-Worach commented
@MatWisie Now everything is how supposted to be
Reverted commits that were supposted to be on favourited controller branch

2024-11-30 12:14 UTC, MatWisie approved these changes

2024-11-30 12:16 UTC, merged