10 add interactive map with kebab information to admin panel
MatWisie/KebabFinder-API pull request #32
Opened 2024-11-28 16:16 UTC by Wiktor-Wojciechowski

This should close #10 

- Added an interactive map with kebab information
- Made small fixes to other pages

Please check if everything is okay

2024-11-29 22:14 UTC, MatWisie requested changes
1. In kebab list last item has "Show More" button overflow
![obraz](https://github.com/user-attachments/assets/e9f73a88-f5c6-4a82-83da-20e07881bcc8)

2. Shouldn't map be visible only for auth admin? After all its admin panel.

2024-11-30 11:02 UTC, MatWisie requested changes
All right, this pull request will be approved after https://github.com/MatWisie/KebabFinder-API/pull/30 has been merged as I need to check it with newest possible comments controller

2024-12-01 13:51 UTC, W-Worach commented
![image](https://github.com/user-attachments/assets/bab84021-5faa-4b5f-b47f-70804b1eefc0)
Also I would suggest to make categories (opening hours, souces, meat types etc) to make text bold to highlight them from their informations

2024-12-01 13:52 UTC, W-Worach requested changes

2024-12-01 13:52 UTC, W-Worach commented on KebabBackend/routes/api.php
This route should only for admin because it returns informations that ordinary user shouldn't see (i.e. email address, created_at and etc)

2024-12-01 13:52 UTC, W-Worach commented on KebabBackend/app/Services/CommentService.php
Same situation there i dont think everyone should see all user informations, just the name and is_admin should be enought

2024-12-03 13:15 UTC, W-Worach approved these changes

2024-12-03 17:49 UTC, MatWisie approved these changes

2024-12-03 18:11 UTC, merged