5 make favourite controller
MatWisie/KebabFinder-API pull request #33
Opened 2024-11-30 12:23 UTC by W-Worach

Added favourite controller with functions
 - add to favourites
 - remove from favourites
 - get user favourites

2024-12-05 14:55 UTC, Wiktor-Wojciechowski requested changes
I suggest to change these paths in the docs to fit with the rest and keep them consistent.
Remember to pull from main before merging too as this branch does not have the updated paths in other places

2024-12-05 14:55 UTC, Wiktor-Wojciechowski commented on KebabBackend/app/Http/Controllers/Api/FavouriteController.php
> +     *     path="/kebabs/{kebab}/favourite",
```suggestion
     *     path="/api/kebabs/{kebab}/favourite",
```

2024-12-05 14:55 UTC, Wiktor-Wojciechowski commented on KebabBackend/app/Http/Controllers/Api/FavouriteController.php
> +     *     path="/kebabs/{kebab}/favourite",
```suggestion
     *     path="/api/kebabs/{kebab}/favourite",
```

2024-12-05 14:55 UTC, Wiktor-Wojciechowski commented on KebabBackend/app/Http/Controllers/Api/FavouriteController.php
> +     *     path="/user/favourites",
```suggestion
     *     path="/api/user/favourites",
```

2024-12-07 22:32 UTC, MatWisie approved these changes
New, favourite routes, are not visible in swagger documentation. Include it in documentation and its good to go
![obraz](https://github.com/user-attachments/assets/3eef679e-6970-486f-ab32-de7ea64bb2d9)

2024-12-08 13:44 UTC, Wiktor-Wojciechowski approved these changes

2024-12-08 13:59 UTC, merged