14 admin add kebab panel
MatWisie/KebabFinder-API pull request #35
Opened 2024-12-10 18:47 UTC by Wiktor-Wojciechowski

This should close #14

2024-12-15 18:23 UTC, W-Worach requested changes
![image](https://github.com/user-attachments/assets/f36952a0-72b4-4230-bfae-78c99ae12013)

in adding kebab view there should be option to set that kebab in selected day is closed

2024-12-18 17:05 UTC, W-Worach approved these changes

2024-12-18 18:26 UTC, MatWisie requested changes
In this image there are two things that need fixing:
1. Wednesday is closed (thats good) but i didnt touch saturday and sunday, yet the hours are broken right now (only in saturday and sunday).
2. In ways to order when i leave phone number empty, there is still text "Phone number:". So either write something like "Phone number: - " and repeat it for every "row" or remove Phone number if there is no phone number assigned.
![obraz](https://github.com/user-attachments/assets/d4f77851-3699-4833-9efc-d4915604278a)

2024-12-22 19:12 UTC, MatWisie approved these changes

2024-12-22 19:12 UTC, merged